apiVersion: v1
data:
  app-config.yaml: |
    app:
      title: My Red Hat Developer Hub
      baseUrl: http://redhat-developer-hub-actions-rose.apps.dancurran-lab2025.opdev.io/
    integrations:
      github:
        - host: github.com
          token: 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
    auth:
      providers:
        guest:
          dangerouslyAllowSignInWithoutUserInCatalog: true
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"app-config-rhdh.yaml":"app:\n  title: My Red Hat Developer Hub\n  baseUrl:https://redhat-developer-hub-rose.apps.dancurran-lab2025.opdev.io/\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"app-config-rhdh","namespace":"danspace"}}
  name: app-config-rhdh
  namespace: rose-test