apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: developer-hub-operator-group
  namespace: rhdh-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: demo-project-operator-group
  namespace: demo-project #project-namespace
spec:
  targetNamespaces:
    - demo-project
