kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dynamic-plugins-root # persistent volume to be used in the caching of the dynamic plugin installation
  namespace: rose #project-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
