name: Dynamic plugin smoke tests
on: 
  #push:
  workflow_dispatch:

env:
  TEST_PLUGIN_NS: '@solo.io'
  TEST_PLUGIN_NAME: 'platform-portal-backstage-plugin-backend'
  TEST_PLUGIN_REPO: 'solo-io/platform-portal-backstage-plugin-backend'
  TEST_PLUGIN_REPO_REF: '90463fe991ab23ce59b1573f3417e9532292f753'
  TEST_PLUGIN_LOCAL_DIR:  pluginsrc
  TEST_PLUGIN_TYPE: backend-plugin

jobs:
  build-and-publish:
    name: Build and Publish RHDH Dynamic Plugin
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout respository
        uses: actions/checkout@v4
        
      - name: Install OS deps
        run: |
          sudo apt install g++ -y

      - name: Pull backstage platform
        id: pull-platform
        uses: rocrisp/dh-plugin-workflow-hackery/.github/actions/pull-platform@main
        with:
          token: ${{ github.token }}
      
      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: 'platform/.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Debug
        working-directory: ${{ steps.pull-platform.outputs.platform-content-dir }}
        run: |
          cd e2e-tests; ls
          
      - name: Change to platform directory
        run: cd ${{ steps.pull-platform.outputs.platform-content-dir }}/e2e-tests
         
      - name: Install dependencies
        uses: backstage/actions/yarn-install@b3c1841fd69e1658ac631afafd0fb140a2309024 # v0.6.17
        with:
          cache-prefix: ${{ runner.os }}-v20
    
      - name: Install Playwright Browser
        working-directory: ${{ steps.pull-platform.outputs.platform-content-dir }}/e2e-tests
        run: |
          pwd; ls; yarn playwright install chromium
          