name: Pull Container Image Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pull-container:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install Podman
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      # Step 2: Pull the Container Image
      - name: Pull Container Image
        run: podman pull quay.io/tkral/backstage-community-plugin-todo

      # Step 3: Verify Pulled Image
      - name: List Podman Images
        run: podman images
